import imaplib 
from imap_tools import MailBox
import requests
from bs4 import BeautifulSoup
from dateutil import parser
from email2text import sendtext

#for marking paid -- will create an endpoint generated by fast api that will mark the spefici bill paid by the specific roomate (send each roomate diff link in text)
#url = "http://127.0.0.1:8000/newbill"
url = "http://127.0.0.1:8000/newbill/"
username = 'householdbills.sc@gmail.com'
password = 'qtyrvtbqfqumhrgv'
imap_server = 'imap.gmail.com'
imap = imaplib.IMAP4_SSL(imap_server)
imap.login(username, password)
status, messages = imap.select("INBOX")
messages = int(messages[0])
print(messages)

def  sendbill(id,provider,btype,amount,date,ogbody):
        jdict = {
                "id": int(id),
                "provider": str(provider),
                "btype": str(btype),
                "amount": float(amount),
                "ogbody": str(ogbody),
                "date":date.strftime("%m/%d/%Y"),
                "fullpaid": False,
                "santipaid": False,
                "johnpaid" : False,
                "liampaid": False,
                "sampaid": False
                }
        
        print(f"Sending bill {jdict['id']} of provider {jdict['provider']}")
        rp = requests.post(url,json=jdict)
        retval = (rp.json())
        status = {retval['status']}
        print(status)
        if 'Success' in str(status):
            numbers = ['5082693523@vzwpix.com',"6175432323@mms.att.net","2159906534@vzwpix.com","64638417289@tmomail.net"]
            users = ['Sam','Liam','John','Santi']
            for i in range(len(numbers)):
                link = "LINK"
                msg = f"{users[i]} You have a new {btype} bill from {provider} for a household total of {amount}, your share is {(float(amount))/4}. Go to {link} to mark paid and to see all household unpaid bills."
                print(f"sent{msg}")
                sendtext({numbers[i]},msg)
 

def find_between( s, first, last ):
    try:
        start = s.index( first ) + len( first )
        end = s.index( last, start )
        return s[start:end]
    except ValueError:
        return ""


# Get date, subject and body len of all emails from INBOX folder
with MailBox(imap_server).login(username,'qtyrvtbqfqumhrgv') as mailbox:
    for msg in mailbox.fetch():
        if "Your bill statement is ready" in msg.subject and 'Xfinity' in msg.html:
            #print(msg.uid,msg.from_,msg.subject,msg.text)
            clean_text = ' '.join(BeautifulSoup(msg.html, "html.parser").stripped_strings)
            print(clean_text)
            amt = find_between(clean_text,"$","Payment")
            date = msg.date_str
            print(date)
            date= (parser.parse(date))
            sendbill(id=msg.uid,provider="Xfinity",btype="Wifi",amount=amt,date=date,ogbody=clean_text)
        if "Your gas bill is ready to view" in msg.subject and 'National Grid' in msg.html:
            clean_text = ' '.join(BeautifulSoup(msg.html, "html.parser").stripped_strings)
            amt = find_between(clean_text,"$","Please")
            date = msg.date_str
            date = (parser.parse(date))
            sendbill(id=msg.uid,provider="National Grid",btype="gas",amount=amt,date=date,ogbody=clean_text,)
        if "New Electric Bill from Eversource" in msg.subject and 'Eversource' in msg.html:
            clean_text = ' '.join(BeautifulSoup(msg.html, "html.parser").stripped_strings)
            amt = find_between(clean_text,"$","Account")
            date = msg.date_str
            date = (parser.parse(date))
            sendbill(id=msg.uid,provider="Eversource",btype="Electric",amount=amt,date=date,ogbody=clean_text)
   
            


        

        
   







