# Generated by Django 4.2.5 on 2023-09-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('btype', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('ogbody', models.TextField()),
                ('date', models.CharField(max_length=255)),
                ('fullpaid', models.BooleanField()),
                ('santipaid', models.BooleanField()),
                ('johnpaid', models.BooleanField()),
                ('liampaid', models.BooleanField()),
                ('sampaid', models.BooleanField()),
            ],
        ),
    ]
